# Generated by Django 3.2.4 on 2021-07-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fair_value', models.FloatField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('uncertainty', models.CharField(max_length=10)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now=True)),
                ('buy', models.FloatField(null=True)),
                ('sell', models.FloatField(null=True)),
                ('stddev', models.FloatField()),
                ('cdf', models.FloatField()),
                ('pdf', models.FloatField()),
                ('strike_discount', models.FloatField()),
                ('profit_percent', models.FloatField()),
                ('cagr', models.FloatField(default=None)),
                ('days_to_exp', models.PositiveSmallIntegerField()),
                ('screened', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.stocksymbol')),
            ],
        ),
    ]
