# Generated by Django 3.2.4 on 2023-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_option_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksymbol',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
