# Generated by Django 3.2.4 on 2024-07-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_stocksymbol_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbol',
            name='update_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
